// ============================================================
// data.js — Updated property database (with real images)
// ============================================================

// ── Egypt Location Data ──────────────────────────────────────
var egyptLocations = {
  "Cairo": {
    "Nasr City": ["El Hay El Ashar", "El Hay El Sabi", "Mostafa El-Nahas"],
    "Heliopolis": ["Al-Merghany", "Alf Maskan", "Korba"],
    "Maadi": ["Maadi Corniche", "Old Maadi", "Degla"],
    "New Cairo": ["Fifth Settlement", "First Settlement", "Rehab City"],
    "6th of October": ["Dream Land", "Al Motamayez", "Hay 11"]
  },
  "Giza": {
    "Dokki": ["Tahrir Square Area", "Lebanon Sq.", "Mesaha Sq."],
    "Haram": ["Faisal St.", "Bawabet Al-Ahram", "Omraneya"],
    "Sheikh Zayed": ["Beverly Hills", "Hay 13", "Zayed 2000"],
    "6th of October": ["Al-Wahat Road", "Kafr Nassar", "Central District"]
  },
  "Alexandria": {
    "Smouha": ["Smouha Gardens", "Geish Road", "Victor Emanuel Sq."],
    "Montaza": ["Al-Mandara", "Asafra", "Abu Qir"],
    "Miami": ["Miami Beach", "Cleopatra", "San Stefano"],
    "Agami": ["Hanouville", "Bittash", "King Mariout"]
  },
  "Assiut": {
    "Assiut City": ["El Walid", "El Hamra", "New Assiut"],
    "Abnub": ["Abnub Center", "El Qusiya", "Sahel Selim"],
    "Dairut": ["Dairut Center", "El Badari", "El Ghanaim"]
  },
  "Luxor": {
    "Luxor City": ["El Awamiya", "Karnak", "El Bayadeya"],
    "Esna": ["Esna Center", "El Tod", "Armant"]
  },
  "Hurghada": {
    "Red Sea": ["Sahl Hasheesh", "El Mamsha", "El Kawther"],
    "El Gouna": ["Kafr El Gouna", "Abu Tig Marina", "Zentour"]
  }
};

// ── Property Categories ──────────────────────────────────────
var CATEGORIES = ["Apartment", "Villa", "Building", "Studio", "Duplex", "Penthouse", "Chalet"];

// ── Property Database ────────────────────────────────────────
var properties = [
  {
    id: 1,
    title: "Spacious Family Apartment",
    governorate: "Cairo",
    district: "Nasr City",
    area: "El Hay El Ashar",
    category: "Apartment",
    price: 1850000,
    size: 180,
    bedrooms: 3,
    bathrooms: 2,
    floor: 4,
    description: "Bright 3-bedroom apartment with modern finishes.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
    available: true,
    year: 2018
  },
  {
    id: 2,
    title: "Cozy Studio — City Center",
    governorate: "Cairo",
    district: "Nasr City",
    area: "El Hay El Sabi",
    category: "Studio",
    price: 650000,
    size: 55,
    bedrooms: 1,
    bathrooms: 1,
    floor: 2,
    description: "Modern studio perfect for singles.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    available: true,
    year: 2020
  },
  {
    id: 3,
    title: "Luxury Penthouse",
    governorate: "Cairo",
    district: "New Cairo",
    area: "Fifth Settlement",
    category: "Penthouse",
    price: 6500000,
    size: 320,
    bedrooms: 4,
    bathrooms: 3,
    floor: 12,
    description: "Luxury penthouse with rooftop.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    available: true,
    year: 2022
  },
  {
    id: 4,
    title: "Modern Duplex Villa",
    governorate: "Cairo",
    district: "New Cairo",
    area: "Rehab City",
    category: "Duplex",
    price: 4200000,
    size: 260,
    bedrooms: 4,
    bathrooms: 3,
    floor: 1,
    description: "Duplex with private garden.",
    image: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c",
    available: true,
    year: 2021
  },
  {
    id: 5,
    title: "Classic Heliopolis Apartment",
    governorate: "Cairo",
    district: "Heliopolis",
    area: "Korba",
    category: "Apartment",
    price: 2300000,
    size: 200,
    bedrooms: 3,
    bathrooms: 2,
    floor: 3,
    description: "Elegant classic apartment.",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
    available: true,
    year: 2005
  },
  {
    id: 6,
    title: "Modern Villa",
    governorate: "Giza",
    district: "Sheikh Zayed",
    area: "Beverly Hills",
    category: "Villa",
    price: 9800000,
    size: 500,
    bedrooms: 5,
    bathrooms: 4,
    floor: 0,
    description: "Luxury villa with pool.",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227",
    available: true,
    year: 2023
  },
  {
    id: 7,
    title: "Affordable Apartment",
    governorate: "Giza",
    district: "Dokki",
    area: "Tahrir Square Area",
    category: "Apartment",
    price: 1100000,
    size: 120,
    bedrooms: 2,
    bathrooms: 1,
    floor: 5,
    description: "Good for investment.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    available: true,
    year: 2012
  },
  {
    id: 8,
    title: "Investment Building",
    governorate: "Giza",
    district: "Haram",
    area: "Faisal St.",
    category: "Building",
    price: 15000000,
    size: 1200,
    bedrooms: 0,
    bathrooms: 0,
    floor: 0,
    description: "Full building investment.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab",
    available: true,
    year: 2010
  },
  {
    id: 9,
    title: "Sea View Apartment",
    governorate: "Alexandria",
    district: "Miami",
    area: "San Stefano",
    category: "Apartment",
    price: 3100000,
    size: 175,
    bedrooms: 3,
    bathrooms: 2,
    floor: 7,
    description: "Sea view apartment.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    available: true,
    year: 2019
  },
  {
    id: 10,
    title: "Beach Chalet",
    governorate: "Alexandria",
    district: "Agami",
    area: "Hanouville",
    category: "Chalet",
    price: 1650000,
    size: 90,
    bedrooms: 2,
    bathrooms: 1,
    floor: 1,
    description: "Near the beach.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    available: true,
    year: 2017
  },
  {
    id: 11,
    title: "Resort Chalet",
    governorate: "Hurghada",
    district: "Red Sea",
    area: "Sahl Hasheesh",
    category: "Chalet",
    price: 2200000,
    size: 100,
    bedrooms: 2,
    bathrooms: 2,
    floor: 2,
    description: "Inside resort.",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    available: true,
    year: 2021
  },
  {
    id: 12,
    title: "Marina Studio",
    governorate: "Hurghada",
    district: "El Gouna",
    area: "Abu Tig Marina",
    category: "Studio",
    price: 950000,
    size: 60,
    bedrooms: 1,
    bathrooms: 1,
    floor: 1,
    description: "Marina view.",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
    available: true,
    year: 2020
  },
  // ── New properties (ids 13–40) ───────────────────────────────
  {
    id: 13,
    title: "Maadi Garden Apartment",
    governorate: "Cairo",
    district: "Maadi",
    area: "Old Maadi",
    category: "Apartment",
    price: 2750000,
    size: 210,
    bedrooms: 3,
    bathrooms: 2,
    floor: 2,
    description: "Quiet garden-facing apartment in leafy Old Maadi.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00",
    available: true,
    year: 2016
  },
  {
    id: 14,
    title: "Maadi Corniche Studio",
    governorate: "Cairo",
    district: "Maadi",
    area: "Maadi Corniche",
    category: "Studio",
    price: 720000,
    size: 58,
    bedrooms: 1,
    bathrooms: 1,
    floor: 3,
    description: "Compact studio overlooking the Nile Corniche.",
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb",
    available: true,
    year: 2019
  },
  {
    id: 15,
    title: "October Duplex",
    governorate: "Cairo",
    district: "6th of October",
    area: "Al Motamayez",
    category: "Duplex",
    price: 3100000,
    size: 230,
    bedrooms: 4,
    bathrooms: 3,
    floor: 1,
    description: "Spacious duplex in a quiet compound.",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914",
    available: true,
    year: 2020
  },
  {
    id: 16,
    title: "Heliopolis Sky Penthouse",
    governorate: "Cairo",
    district: "Heliopolis",
    area: "Alf Maskan",
    category: "Penthouse",
    price: 5200000,
    size: 290,
    bedrooms: 4,
    bathrooms: 3,
    floor: 10,
    description: "High-floor penthouse with panoramic city views.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    available: true,
    year: 2021
  },
  {
    id: 17,
    title: "First Settlement Villa",
    governorate: "Cairo",
    district: "New Cairo",
    area: "First Settlement",
    category: "Villa",
    price: 8500000,
    size: 450,
    bedrooms: 5,
    bathrooms: 4,
    floor: 0,
    description: "Corner villa with large private garden.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9",
    available: true,
    year: 2022
  },
  {
    id: 18,
    title: "Dream Land Chalet",
    governorate: "Cairo",
    district: "6th of October",
    area: "Dream Land",
    category: "Chalet",
    price: 1400000,
    size: 85,
    bedrooms: 2,
    bathrooms: 1,
    floor: 1,
    description: "Cozy chalet inside Dream Land compound.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2",
    available: true,
    year: 2018
  },
  {
    id: 19,
    title: "Sheikh Zayed Studio",
    governorate: "Giza",
    district: "Sheikh Zayed",
    area: "Hay 13",
    category: "Studio",
    price: 780000,
    size: 62,
    bedrooms: 1,
    bathrooms: 1,
    floor: 4,
    description: "Modern studio close to malls and services.",
    image: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9",
    available: true,
    year: 2021
  },
  {
    id: 20,
    title: "Zayed 2000 Apartment",
    governorate: "Giza",
    district: "Sheikh Zayed",
    area: "Zayed 2000",
    category: "Apartment",
    price: 1750000,
    size: 155,
    bedrooms: 3,
    bathrooms: 2,
    floor: 6,
    description: "Well-finished apartment in a popular residential area.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    available: true,
    year: 2017
  },
  {
    id: 21,
    title: "Dokki Commercial Building",
    governorate: "Giza",
    district: "Dokki",
    area: "Lebanon Sq.",
    category: "Building",
    price: 22000000,
    size: 1800,
    bedrooms: 0,
    bathrooms: 0,
    floor: 0,
    description: "8-floor mixed-use building on Lebanon Square.",
    image: "https://images.unsplash.com/photo-1464082354059-27db6ce50048",
    available: true,
    year: 2008
  },
  {
    id: 22,
    title: "Omraneya Family Villa",
    governorate: "Giza",
    district: "Haram",
    area: "Omraneya",
    category: "Villa",
    price: 4800000,
    size: 380,
    bedrooms: 5,
    bathrooms: 3,
    floor: 0,
    description: "Spacious villa with garden and rooftop.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    available: true,
    year: 2015
  },
  {
    id: 23,
    title: "Wahat Road Duplex",
    governorate: "Giza",
    district: "6th of October",
    area: "Al-Wahat Road",
    category: "Duplex",
    price: 2600000,
    size: 200,
    bedrooms: 3,
    bathrooms: 2,
    floor: 1,
    description: "Two-floor duplex with open desert views.",
    image: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c",
    available: true,
    year: 2019
  },
  {
    id: 24,
    title: "Smouha Luxury Apartment",
    governorate: "Alexandria",
    district: "Smouha",
    area: "Smouha Gardens",
    category: "Apartment",
    price: 2900000,
    size: 190,
    bedrooms: 3,
    bathrooms: 2,
    floor: 5,
    description: "Upscale apartment near Smouha Club.",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00",
    available: true,
    year: 2020
  },
  {
    id: 25,
    title: "Montaza Sea Apartment",
    governorate: "Alexandria",
    district: "Montaza",
    area: "Al-Mandara",
    category: "Apartment",
    price: 2400000,
    size: 165,
    bedrooms: 3,
    bathrooms: 2,
    floor: 4,
    description: "Apartment steps from Montaza Palace gardens.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    available: true,
    year: 2018
  },
  {
    id: 26,
    title: "Asafra Beachfront Studio",
    governorate: "Alexandria",
    district: "Montaza",
    area: "Asafra",
    category: "Studio",
    price: 870000,
    size: 65,
    bedrooms: 1,
    bathrooms: 1,
    floor: 2,
    description: "Sea-facing studio with private balcony.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    available: true,
    year: 2021
  },
  {
    id: 27,
    title: "Miami Beach Penthouse",
    governorate: "Alexandria",
    district: "Miami",
    area: "Miami Beach",
    category: "Penthouse",
    price: 4700000,
    size: 280,
    bedrooms: 4,
    bathrooms: 3,
    floor: 9,
    description: "Top-floor penthouse with full sea view.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750",
    available: true,
    year: 2022
  },
  {
    id: 28,
    title: "Agami Summer Chalet",
    governorate: "Alexandria",
    district: "Agami",
    area: "Bittash",
    category: "Chalet",
    price: 1350000,
    size: 80,
    bedrooms: 2,
    bathrooms: 1,
    floor: 1,
    description: "Furnished summer chalet with pool access.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
    available: true,
    year: 2016
  },
  {
    id: 29,
    title: "Smouha Investment Building",
    governorate: "Alexandria",
    district: "Smouha",
    area: "Geish Road",
    category: "Building",
    price: 18000000,
    size: 1400,
    bedrooms: 0,
    bathrooms: 0,
    floor: 0,
    description: "Fully rented 7-floor building on Geish Road.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab",
    available: true,
    year: 2011
  },
  {
    id: 30,
    title: "New Assiut Apartment",
    governorate: "Assiut",
    district: "Assiut City",
    area: "New Assiut",
    category: "Apartment",
    price: 850000,
    size: 160,
    bedrooms: 3,
    bathrooms: 2,
    floor: 3,
    description: "Modern apartment in new development area.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
    available: true,
    year: 2022
  },
  {
    id: 31,
    title: "El Hamra Family Villa",
    governorate: "Assiut",
    district: "Assiut City",
    area: "El Hamra",
    category: "Villa",
    price: 2500000,
    size: 350,
    bedrooms: 5,
    bathrooms: 3,
    floor: 0,
    description: "Generous villa with garden and rooftop.",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227",
    available: true,
    year: 2016
  },
  {
    id: 32,
    title: "El Walid Budget Studio",
    governorate: "Assiut",
    district: "Assiut City",
    area: "El Walid",
    category: "Studio",
    price: 420000,
    size: 48,
    bedrooms: 1,
    bathrooms: 1,
    floor: 2,
    description: "Affordable studio ideal for students.",
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb",
    available: true,
    year: 2019
  },
  {
    id: 33,
    title: "Abnub Investment Building",
    governorate: "Assiut",
    district: "Abnub",
    area: "Abnub Center",
    category: "Building",
    price: 7500000,
    size: 900,
    bedrooms: 0,
    bathrooms: 0,
    floor: 0,
    description: "5-floor building in central Abnub.",
    image: "https://images.unsplash.com/photo-1464082354059-27db6ce50048",
    available: true,
    year: 2013
  },
  {
    id: 34,
    title: "Karnak View Apartment",
    governorate: "Luxor",
    district: "Luxor City",
    area: "Karnak",
    category: "Apartment",
    price: 1100000,
    size: 130,
    bedrooms: 2,
    bathrooms: 2,
    floor: 3,
    description: "Apartment near Karnak Temple with Nile views.",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
    available: true,
    year: 2017
  },
  {
    id: 35,
    title: "Luxor Nile Villa",
    governorate: "Luxor",
    district: "Luxor City",
    area: "El Awamiya",
    category: "Villa",
    price: 3800000,
    size: 320,
    bedrooms: 4,
    bathrooms: 3,
    floor: 0,
    description: "Villa with Nile-facing garden and terrace.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9",
    available: true,
    year: 2020
  },
  {
    id: 36,
    title: "Esna Town Apartment",
    governorate: "Luxor",
    district: "Esna",
    area: "Esna Center",
    category: "Apartment",
    price: 680000,
    size: 110,
    bedrooms: 2,
    bathrooms: 1,
    floor: 2,
    description: "Affordable apartment in Esna city center.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    available: true,
    year: 2015
  },
  {
    id: 37,
    title: "El Kawther Chalet",
    governorate: "Hurghada",
    district: "Red Sea",
    area: "El Kawther",
    category: "Chalet",
    price: 1900000,
    size: 95,
    bedrooms: 2,
    bathrooms: 2,
    floor: 1,
    description: "Furnished chalet with pool in El Kawther.",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b",
    available: true,
    year: 2020
  },
  {
    id: 38,
    title: "El Mamsha Studio",
    governorate: "Hurghada",
    district: "Red Sea",
    area: "El Mamsha",
    category: "Studio",
    price: 820000,
    size: 55,
    bedrooms: 1,
    bathrooms: 1,
    floor: 3,
    description: "Studio on the famous El Mamsha promenade.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    available: true,
    year: 2021
  },
  {
    id: 39,
    title: "Gouna Zentour Duplex",
    governorate: "Hurghada",
    district: "El Gouna",
    area: "Zentour",
    category: "Duplex",
    price: 3500000,
    size: 220,
    bedrooms: 3,
    bathrooms: 2,
    floor: 1,
    description: "Two-floor duplex inside El Gouna resort island.",
    image: "https://images.unsplash.com/photo-1572120360610-d971b9d7767c",
    available: true,
    year: 2022
  },
  {
    id: 40,
    title: "Gouna Kafr Villa",
    governorate: "Hurghada",
    district: "El Gouna",
    area: "Kafr El Gouna",
    category: "Villa",
    price: 7200000,
    size: 410,
    bedrooms: 5,
    bathrooms: 4,
    floor: 0,
    description: "Standalone villa in the charming Kafr El Gouna village.",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227",
    available: true,
    year: 2023
  },
  {
    id: 41,
    title: "Degla Penthouse",
    governorate: "Cairo",
    district: "Maadi",
    area: "Degla",
    category: "Penthouse",
    price: 4900000,
    size: 300,
    bedrooms: 4,
    bathrooms: 3,
    floor: 11,
    description: "Elegant penthouse in Degla with private rooftop terrace and Nile glimpse.",
    image: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e",
    available: true,
    year: 2021
  },
  {
    id: 42,
    title: "Al-Merghany Apartment",
    governorate: "Cairo",
    district: "Heliopolis",
    area: "Al-Merghany",
    category: "Apartment",
    price: 1980000,
    size: 170,
    bedrooms: 3,
    bathrooms: 2,
    floor: 5,
    description: "Well-maintained apartment in a prestigious Heliopolis street.",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
    available: true,
    year: 2014
  },
  {
    id: 43,
    title: "Hay 11 Budget Apartment",
    governorate: "Cairo",
    district: "6th of October",
    area: "Hay 11",
    category: "Apartment",
    price: 950000,
    size: 115,
    bedrooms: 2,
    bathrooms: 1,
    floor: 3,
    description: "Affordable apartment ideal for young families in 6th of October.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2",
    available: true,
    year: 2015
  },
  {
    id: 44,
    title: "Mesaha Square Studio",
    governorate: "Giza",
    district: "Dokki",
    area: "Mesaha Sq.",
    category: "Studio",
    price: 690000,
    size: 52,
    bedrooms: 1,
    bathrooms: 1,
    floor: 6,
    description: "Bright studio in the heart of Dokki near Mesaha Square.",
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb",
    available: true,
    year: 2020
  },
  {
    id: 45,
    title: "Kafr Nassar Duplex",
    governorate: "Giza",
    district: "6th of October",
    area: "Kafr Nassar",
    category: "Duplex",
    price: 2350000,
    size: 195,
    bedrooms: 3,
    bathrooms: 2,
    floor: 1,
    description: "Two-storey duplex with a small private garden in a calm neighbourhood.",
    image: "https://images.unsplash.com/photo-1576941089067-2de3c901e126",
    available: true,
    year: 2018
  },
  {
    id: 46,
    title: "Abu Qir Seaside Apartment",
    governorate: "Alexandria",
    district: "Montaza",
    area: "Abu Qir",
    category: "Apartment",
    price: 1850000,
    size: 145,
    bedrooms: 3,
    bathrooms: 2,
    floor: 4,
    description: "Seafront apartment in Abu Qir with stunning Mediterranean views.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    available: true,
    year: 2017
  },
  {
    id: 47,
    title: "Cleopatra Luxury Apartment",
    governorate: "Alexandria",
    district: "Miami",
    area: "Cleopatra",
    category: "Apartment",
    price: 2650000,
    size: 180,
    bedrooms: 3,
    bathrooms: 2,
    floor: 6,
    description: "Spacious apartment in Cleopatra district close to the Corniche.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688",
    available: true,
    year: 2019
  },
  {
    id: 48,
    title: "El Bayadeya Apartment",
    governorate: "Luxor",
    district: "Luxor City",
    area: "El Bayadeya",
    category: "Apartment",
    price: 790000,
    size: 120,
    bedrooms: 2,
    bathrooms: 1,
    floor: 2,
    description: "Affordable apartment on the west bank of Luxor with local charm.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    available: true,
    year: 2016
  },
  {
    id: 49,
    title: "El Dairut Building",
    governorate: "Assiut",
    district: "Dairut",
    area: "Dairut Center",
    category: "Building",
    price: 6200000,
    size: 780,
    bedrooms: 0,
    bathrooms: 0,
    floor: 0,
    description: "4-floor residential building fully tenanted in Dairut center.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab",
    available: true,
    year: 2012
  },
  {
    id: 50,
    title: "Sahl Hasheesh Villa",
    governorate: "Hurghada",
    district: "Red Sea",
    area: "Sahl Hasheesh",
    category: "Villa",
    price: 11500000,
    size: 550,
    bedrooms: 6,
    bathrooms: 5,
    floor: 0,
    description: "Beachfront villa inside the exclusive Sahl Hasheesh resort with private pool.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9",
    available: true,
    year: 2023
  }
];

// ── Helper: next available ID ────────────────────────────────
function getNextId() {
  return properties.reduce((max, p) => (p.id > max ? p.id : max), 0) + 1;
}
let cards = document.getElementById("card-continer");
let show = [];
properties.slice(0,11).forEach(function (property) {
  if (!show.includes(property.district)) {
    show.push(property.district)

    cards.innerHTML += `
        <div class="card" id="card">
            <img src="${property.image}" alt="${property.title}" class="card-image">
            <div class="card-content">
                <h3 class="card-title">${property.title}</h3>
                <p class="card-location">
                 <i class="fa-solid fa-location-dot"></i> ${property.governorate} / ${property.district} / ${property.area}
                </p>
                <p class="card-price">
                 <i class="fa-solid fa-sack-dollar"></i> ${property.price.toLocaleString()} EGP
                </p>
                <div class="card-specs">
                    <span> <i class="fa-solid fa-bed"></i> ${property.bedrooms} room</span>
                    <span><i class="fa-solid fa-bath"></i> ${property.bathrooms} bathroom</span>
                    <span><i class="fa-solid fa-arrows-up-down-left-right"></i> ${property.size} m²</span>
                </div>
                <p class="card-category">
                    ${property.category} • ${property.year} year
                </p>
            </div>
        </div>
    `;
  }
})

